#import "../config/thesis-config.typ": glpl, gl, linkfn
#import "../config/variables.typ": myTutor
#pagebreak(to:"odd")

= Stato dell'Arte<cap:stato-arte>
#text(style: "italic", [
    In questo capitolo ripercorro lo stato dell'arte su cui si fonda il progetto: l'evoluzione dei Large Language Models, il paradigma del tool use e della function calling, il Model Context Protocol e i principali framework di orchestrazione per applicazioni basate su intelligenza artificiale.
])
#v(1em)

== L'evoluzione dei Large Language Models
Gli LLM hanno conosciuto negli ultimi anni un'evoluzione radicale, ridefinendo i confini dell'ingegneria del software e dell'intelligenza artificiale applicata. Basati prevalentemente sull'architettura #linkfn("https://arxiv.org/abs/1706.03762")[Transformer] introdotta da Vaswani et al. nel 2017 @vaswani2017, questi modelli vengono pre-addestrati su enormi volumi di testo non strutturato per apprendere le relazioni statistiche e semantiche tra i _token_. \
Inizialmente concepiti come predittori statistici di testo, i modelli più recenti hanno mostrato capacità emergenti avanzate, tra cui il ragionamento logico-deduttivo, la comprensione del contesto e la generazione di codice sorgente sintatticamente corretto. Sebbene posseggano queste potentissime capacità, l'architettura pura di un LLM presenta un limite intrinseco, l'_isolamento informativo_: il modello risponde basandosi esclusivamente sulla conoscenza cristallizzata al momento del suo #gl("knowledge-cutoff"), risultando cieco rispetto ai dati dinamici, in tempo reale o privati. A ciò si aggiunge il fenomeno delle _allucinazioni_, ovvero la generazione di risposte plausibili ma fattualmente errate.

== Il paradigma del Tool Use e della Function Calling
Per superare l'isolamento informativo e ridurre l'incidenza delle #gl("allucinazione"), la ricerca si è orientata verso #gl("sistemi-aumentati"), facendo evolvere il ruolo dell'LLM da generatore di testo ad _agente_ in grado di interagire con l'ambiente esterno. Questo cambiamento di paradigma è noto come _tool use_ o _function calling_.\
In questo modello l'LLM non viene più interrogato per fornire direttamente la risposta a un problema che richiede dati esterni; viene invece istruito a riconoscere quando una richiesta necessita di informazioni integrative o di un'azione applicativa. In tal caso il modello interrompe la generazione e produce un output strutturato --- tipicamente in formato #gl("json") --- che specifica il nome di una funzione e i relativi parametri di invocazione. L'applicazione ospite intercetta questo output, esegue la funzione chiamando le _API_ o effettuando le query necessarie e restituisce il risultato al modello, che lo rielabora per formulare la risposta finale. Il meccanismo sposta il carico dell'elaborazione del dato dall'intelligenza artificiale al software deterministico, garantendo la precisione del risultato.

== Il Model Context Protocol
Sebbene la _function calling_ sia ampiamente supportata dai principali provider di modelli, la sua implementazione ha storicamente sofferto di una forte frammentazione. Prima dell'avvento di MCP, l'integrazione tra LLM e strumenti esterni era affidata a meccanismi proprietari e mutuamente incompatibili: le _OpenAI Functions_ definivano i _tool_ tramite uno schema JSON specifico con vincoli di formato rigidi; _Anthropic Tool Use_ adottava un proprio schema di descrizione e un diverso protocollo di invocazione; i #gl("plugin") system di ChatGPT imponevano un modello di autenticazione e manifest separato. Ogni piattaforma e ogni framework imponeva quindi schemi di definizione dei tool, formati di serializzazione e modelli di trasporto proprietari. Di conseguenza, integrare lo stesso set di strumenti con modelli differenti ha spesso richiesto la riscrittura di complessi _layer_ di adattamento.\
Per risolvere il suddetto problema di interoperabilità è stato introdotto il #linkfn("https://modelcontextprotocol.io/docs/getting-started/intro")[Model Context Protocol] @mcp-spec, un protocollo aperto e standardizzato --- sviluppato da Anthropic#footnote[Società statunitense di ricerca e sviluppo nell'intelligenza artificiale.] @anthropic --- che formalizza la comunicazione tra le applicazioni guidate dall'AI e le sorgenti di dati o strumenti esterni. Per analogia, il protocollo MCP rappresenta per un'applicazione basata su intelligenza artificiale ciò che lo standard USB-C rappresenta per l'hardware: un livello di connessione universale.\

L'architettura si basa su una chiara separazione dei ruoli secondo un pattern _host-client-server_. Un *server MCP* è un processo indipendente che espone in modo standardizzato tre tipi di risorse primitive: i #gl("prompt") (modelli di istruzioni preconfigurati), le _resource_ (dati testuali o binari in sola lettura) e i _tool_ (funzioni eseguibili che interrogano o modificano sistemi esterni, descritte tramite JSON Schema). Un *host* --- come un #gl("ide") o un assistente conversazionale --- istanzia, per ciascun server a cui si collega, un *client MCP* che ne media la comunicazione: il client interroga il server per scoprirne le capacità, ne inoltra gli schemi al modello e, quando questo richiede l'invocazione di uno strumento, instrada la chiamata al server e ne restituisce la risposta.\

#figure(
    caption: [Rappresentazione architetturale di alto livello del Model Context Protocol (MCP).\ *Source:* _#link("https://modelcontextprotocol.io/docs/getting-started/intro")_ @mcp-spec],
    image("../images/mcp-simple-diagram.png", width: 120%)
)<fig:mcp-diagram>

A livello di trasporto il protocollo utilizza canali standard --- i flussi di input/output standard (_stdio_) per processi locali o connessioni persistenti (come i _Server Sent Events_ su HTTP) per le architetture distribuite --- serializzando i messaggi secondo lo standard JSON-RPC 2.0.

== Framework di orchestrazione e vincoli aziendali
La traduzione pratica del paradigma ad agenti in contesti _enterprise_ richiede framework di orchestrazione robusti, capaci di gestire i cicli di esecuzione, i contesti di memoria e i filtri software. Nel panorama Microsoft i due principali riferimenti sono #linkfn("https://www.langchain.com/")[LangChain] @langchain e #linkfn("https://learn.microsoft.com/it-it/semantic-kernel/overview/")[Microsoft Semantic Kernel] @semantic-kernel.\

Semantic Kernel è un #gl("sdk") _open source_ sviluppato da Microsoft per facilitare l'integrazione di modelli AI in applicazioni .NET. Rispetto ad altre librerie si distingue per una forte astrazione concettuale e per un'integrazione nativa con i meccanismi di _dependency injection_ e di programmazione asincrona tipici del C\#. Il framework astrae i canali di comunicazione con i differenti provider AI, offrendo un'interfaccia unificata per la gestione dello _streaming_ dei token e per l'esecuzione dei plugin; si presta quindi come strato ideale per implementare i filtri di controllo e di sicurezza che intercettano le risposte dell'LLM prima della loro visualizzazione.\

LangChain è un'alternativa _open-source_ anche per l'ecosistema Microsoft e Python, meno integrata con .NET Framework ma più flessibile.
Nel progetto non è stata utilizzata perchè Semantic Kernel offre una migliore astrazione per il contesto .NET e una più stretta integrazione con i meccanismi di _dependency injection_ nativi di C\#.
LangChain sarebbe stata la scelta preferita in un ecosistema _polyglot_, ma l'eterogeneità dei _runtime_ (.NET 4.8 _legacy_ vs .NET 10 moderno, cfr. @cap:tecnologie-utilizzate) avrebbe richiesto ulteriori _layer_ di traduzione.

Lo sviluppo di soluzioni basate su queste tecnologie deve però fare i conti con le infrastrutture aziendali preesistenti. Molti ERP di classe _enterprise_ poggiano su versioni classiche del framework .NET --- come .NET Framework 4.8 --- che presentano rigidi vincoli di compatibilità verso le librerie moderne pensate per .NET Core o .NET 8/10. Questa asimmetria tecnologica impone scelte architetturali mirate, separando nettamente l'interfaccia utente _legacy_ dai moderni motori di orchestrazione AI mediante strategie di disaccoppiamento basate su processi locali isolati o servizi web dedicati.